# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4db0c54e4414669ce15ab6c3c429cfd9bec40f00822d8c0fd90acda79b6d05c0fbc910980d5196aedc25d05b705b66ab01e05995ec7c9c47f45c6cd7e8fafb15

test:
  secret_key_base: d50c2e82b5390c4dd50305672e14da0b1e4001a89c7a2a94fbd4b84226ec8f52da7fe64db101f65766abeae76cd445543b0ee5ec582288fed302f3d22fb7af12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
