# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c3f78fa7647cc834e2c1ba96c105ca8233ded8f2ea855aa682f0ba95c66f7130ae772aad81d954b34eb15e7920ed43541aa39b473c4cf79d3ef0a3c09da7ef8

test:
  secret_key_base: 72b1a4680d0a120bdeb6becc5c6f09fd7953a193f0fd32171dfe26bf3e1c1d36591e0bdeba2ae434c3de197118c6c7c06b2043fce1fad757a65cafbe18143c49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
