# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63a14c7bed8c6f9151dfd3b990b15350cd02bcd9869c3056dba5d2d0f31c4dc05e12a16911888c8ab0f23b3fd793539c5b7d74d5e871b3ce43e14b511b820a85

test:
  secret_key_base: 69e48d79d56c0d6f585b9cd055a3b1b16a1974f90f2c9dac943b3c8c7ad2fd2a64478e062c0b395c2399c0f54479eb8f479480ed2841afb740013a25de12ba85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
